language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --dev
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
  - phpunit
  - php coverage-checker.php clover.xml 15
  - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 ./src/); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  irc: "irc.freenode.org#zftalk.modules"
